SportStoreForASPMVC5/SportStoreForASPMVC5.WebUI/Models/CartIndexViewModel.cs
using SportStoreForASPMVC.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SportStoreForASPMVC5.WebUI.Models
{
    public class CartIndeViewModel
    {
        public Cart cart { get; set; }
        public string ResultURL { get; set; }
    }
}

SportStoreForASPMVC5/SportStoreForASPMVC5.WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SportStoreForASPMVC5.WebUI.Models
{
    public class PagingInfo
    {
        public int TotalIteams { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages { get { return (int)Math.Ceiling((decimal)TotalIteams / ItemsPerPage); } }
    }
}

SportStoreForASPMVC5/SportStoreForASPMVC5.WebUI/Models/ProductsListViewModel.cs
using SportStoreForASPMVC.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SportStoreForASPMVC5.WebUI.Models
{
    public class ProductsListViewModel
    {
        public IEnumerable<Product> Products { get; set;}
        public PagingInfo PagingInfo { get; set;}
        public string CurrentCategory { get; set; }
    }
}

SportStoreForASPMVC5/SportStoreForASPMVC5.WebUI/Controllers/CartController.cs
using SportStoreForASPMVC.Domain.Abstract;
using SportStoreForASPMVC.Domain.Entities;
using SportStoreForASPMVC5.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportStoreForASPMVC5.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository Prodrepo;

        public CartController(IProductRepository prodrepo)
        {
            this.Prodrepo = prodrepo;
        }

        public RedirectToRouteResult AddCart(int ProductId, string ReturnUrl)
        {
            Product product = Prodrepo.Products
                .FirstOrDefault(l => l.ProductID == ProductId);

            if (product != null)
            {
                GetCart().AddItem(product, 5);
            }
            return RedirectToAction("Index", new { ReturnUrl });
        }

        public RedirectToRouteResult RemouveFronCart(int ProductId, string RetutnUrl)
        {
            Product product = Prodrepo.Products
                .FirstOrDefault(l => l.ProductID == ProductId);

            if (product != null)
            {
                GetCart().Remouve(product);
            }
            return RedirectToAction("Index", new { RetutnUrl });
        }

        private Cart GetCart()
        {
            Cart cart = (Cart)Session["Cart"];
            if (cart == null)
            {
                cart = new Cart();
                Session["Cart"] = cart;
            }
            return cart;
        }

        public ViewResult Index(string ReturnUrl)
        {
            return View(new CartIndexViewModel
            {
                cart = GetCart(),
                ResultURL = ReturnUrl
            }
                );
        }
    }
}

SportStoreForASPMVC5/SportStoreForASPMVC5.WebUI/Controllers/NavController.cs
using SportStoreForASPMVC.Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportStoreForASPMVC5.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IProductRepository rep;

        public NavController(IProductRepository rep)
        {
            this.rep = rep;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = rep.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);
            return PartialView(categories);
        }
    }
}

SportStoreForASPMVC5/SportStoreForASPMVC5.WebUI/Controllers/ProductController.cs
using SportStoreForASPMVC.Domain.Abstract;
using SportStoreForASPMVC5.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportStoreForASPMVC5.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository productrepository;
        public int Pageinfo = 4;
        public ProductController(IProductRepository producrrepository)
        {
            this.productrepository = producrrepository;
        }

        // GET: Product
        public ViewResult List(string category,int page = 1)
        {
            ProductsListViewModel model = new ProductsListViewModel
            {
                Products = productrepository.Products
                .Where(p => category == null || p.Category == category)
                .OrderBy(p => p.ProductID)
                .Skip((page - 1) * Pageinfo)
                .Take(Pageinfo),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = Pageinfo,
                    TotalIteams = category == null ?
                    productrepository.Products.Count() :
                    productrepository.Products.Where(e => e.Category == category).Count()

                },
                CurrentCategory = category
            };
            return View(model);

        }
    }
}

SportStoreForASPMVC5/SportStoreForASPMVC5.WebUI/Views/Cart/Index.cshtml
@model SportStoreForASPMVC.Domain.Entities.CartIndexViewModel

@{
    ViewBag.Title = "SportStrore youre Cart";
}

<h2> YourCart </h2>
<table class="table">
    <thead>
        <tr>
            <th class="text-center"> Qantyty</th>
            <th class="text-center">Item</th>
            <th class="text-right">Price</th>
            <th class="text-right">Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var line in Model.cart.Lines)
        {
            <tr>
                <td class="text-center">@line.Quantity</td>
                <td class="text-center">@line.Productes.Name</td>
                <td class="text-right">@line.Productes.Price.ToString("c")</td>
                <td class="text-right">@((line.Quantity*line.Productes.Price).ToString("c"))</td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total:</td>
            <td class="text-right">@Model.cart.CalculateValue().ToString("c")</td>
        </tr>
    </tfoot>

</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ResultURL">Continue Shopping</a>

</div>

SportStoreForASPMVC5/SportStoreForASPMVC5.WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>

@Html.ActionLink("Home", "List", "Product", null,
    new { @class = "btn btn-block btn-default btn-lg"})

@foreach(var link in Model)
{
    @Html.RouteLink(link, new
{
    controller = "Product",
    action = "List",
    category = link,
    page = 1}, new { @class = "btn btn-block btn-default btn-lg"
    +(link==ViewBag.SelectedCategory?"btn-primary" : "")})
}

SportStoreForASPMVC5/SportStoreForASPMVC5.WebUI/Views/Product/List.cshtml
@model SportStoreForASPMVC5.WebUI.Models.ProductsListViewModel

@{
    ViewBag.Title = "Products";
}

@foreach(var prod in Model.Products)
{
@Html.Partial("ProductSummary", prod)
}
<div class="btn-group pull-right">
    @Html.PageLinks(Model.PagingInfo, x=> Url.Action("List", new { page = x, category = Model.CurrentCategory }))
</div>

<h2>SomeThing</h2>

SportStoreForASPMVC5/SportStoreForASPMVC5.WebUI/Views/Shared/ProductSummary.cshtml
@model SportStoreForASPMVC.Domain.Entities.Product

    <div class="well">
        <h3>
            <strong>@Model.Name</strong>
            <span class="pull-right label label-primary"> @Model.Price.ToString("c") </span>
        </h3>

        @using (Html.BeginForm("AddCart", "Cart"))
        {
            <div class="pull-right">
                @Html.HiddenFor(x=>x.ProductID)
                @Html.Hidden("returnURL", Request.Url.PathAndQuery)
                <input type="submit" class="btn btn-success" value="Add to Cart"/>
            </div>
        }
        
        @using (Html.BeginForm("RemouveFronCart", "Cart"))
        {
            <div class="pull-right">
                @Html.HiddenFor(x => x.ProductID)
                @Html.Hidden("returnURL", Request.Url.PathAndQuery)
                <input type="submit" class="btn btn-success" value="Remouve from Cart" />
            </div>
        }

        <span class="lead">@Model.Description</span>
    </div>

SportStoreForASPMVC5/SportStoreForASPMVC5.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
            <a class="navbar-brand" href="#">SportStore</a>
    </div>
            <div class="row panel">
                <div id="categories" class="col-xs-3">
                    @Html.Action("Menu","Nav")
                </div>

    <div class="col-xs-8">
        @RenderBody()
    </div>
                </div>
</body>
</html>